### ISSUE TITLE
ACCEPTANCE CRITERA & TASKS

### ISSUE THREAD

**Issue by healygi** [healygi/love-running#3]
In order to **find out what is the best track**, as a **runner**,  I can **vote in a poll**
In order to **gather the votes**, as a **website administrator**,  I can **publish poll results**
In order to **create poll**, as a **developer**,  I can **create a checkbox form using HTML and CSS**

**Acceptance Criteria**

1. The option should be provided as a checkbox
2. The checkbox should be “checked” by default
3. The option should appear next to the submit button
4. After submitting the default submission confirmation should be adjusted to include the user name.
5. The poll should expire at 23:59 and be hidden from the homepage on the target date
6. Results should be published on the target date
7. The real estate of the "Poll" should be reserved on the home page, a message that says "Stay Tuned, a new poll is coming soon" should appear if no other Poll is active.
8. The administrator expiry date should be at least 3 days after the current date. 

**Tasks**

- [ ] Create and design checkbox form poll using HTML and CSS
- [ ] Create a submit button within the form
- [ ] Update form to remember user name after default submission
- [ ] Create different options for best track
- [ ] Collect all data and showcase result
- [ ] Test the completed functionality
- [ ] Create a Javascript function to validate the expiry date is at least 3 days after
